export enum AUTH_ERROR {
  INVALID_CREDENTIALS = '__INVALID_CREDENTIALS__',
  INCORRECT_CREDENTIALS = '__INCORRECT_CREDENTIALS__',
  SERVER_ERROR = '__SERVER_ERROR__'
}

export const sessionCookieId = 'app-session';
