import type { Metadata } from 'next';
import '../../theme/global.scss';
import { Locale } from '@/types/locale';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'es' }];
}

export default function RootLayout({
  children,
  params: { lang }
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang} className="dark">
      <body>{children}</body>
    </html>
  );
}
